### ISSUE TITLE
Hide nav bar links until user is logged in

### ISSUE THREAD

**Issue by scottaj** [scottaj/Course-Outcomes-Assessment-Tool#12]
Right now all of the nav bar links are hard coded. Most of these links should be restricted such that only  logged in users can access them. Therefore all of these links should be programmatcally hidden until the user is logged in to avoid confusing the user.

**Comment by bishopgr** [comment]
ed719265163a310652bdb63d5988206b3948c653 fixed as of 10/3/2012
