### ISSUE TITLE
Restricted paths should redirect to login

### ISSUE THREAD

**Issue by scottaj** [scottaj/Course-Outcomes-Assessment-Tool#13]
Most of the paths in the application require a user to be logged in to view them. If a user tries to navigate to these paths without being logged in they should receive an HTTP _401 UNAUTHORIZED_ error and be redirected to the login page.

**Comment by scottaj** [comment]
Related: Issue #10

**Comment by bishopgr** [comment]
95b219423340bf0e1e952696c23d5e22e56afada Closed as of 10/8/2012.
