### ISSUE TITLE
Replace user deletion with active/inactive flag

### ISSUE THREAD

**Issue by scottaj** [scottaj/Course-Outcomes-Assessment-Tool#26]
Right now users can be deleted. However, it may be useful to see what courses a former professor taught after they have stopped using the system. With our current deletion scheme this information is destroyed when the user is destroyed.

To rectify this, I propose implementing an active/inactive user scheme where no users are ever deleted. Instead of deletion, old users would be marked "inactive". This would prevent them from logging in and showing up in places where you would expect to see current users (course professor selection, etc.) but would preserve their information in the database.

**Comment by bishopgr** [comment]
083a2d78e739b20891650fc8bd25abc0f428c1fd Added as of 10/8/2012.
