### ISSUE TITLE
Dynamic course list on home page

### ISSUE THREAD

**Issue by scottaj** [scottaj/Course-Outcomes-Assessment-Tool#27]
Right now the homepage shows several hard coded courses. Now that courses are implemented as a database entity the homepage should display a dynamic list of unarchived courses assigned to the current user. This could be generated by something like:

``` ruby
Course.find_all_by_user_id_and_archived(params[:token], false)
```

If the user has no active courses it should probably say something like _"No courses available"_ instead.

**Comment by bishopgr** [comment]
035ef3a37ce2b0832a6dafe6a3d3411151404558 Implemented 10/22/2012.
