### ISSUE TITLE
After modifying a user, the user cannot log in

### ISSUE THREAD

**Issue by bishopgr** [scottaj/Course-Outcomes-Assessment-Tool#34]
Once a user is deactivated and then reactivated, they cannot use their account until after their password has been changed once. To remedy this, either an intermediate page has to be implemented right after reactivation, or redirect the user to the edit user page and ensure they can't do anything else but change their password.

**Comment by scottaj** [comment]
Fixed as of: d32fa68de5a504ef142c672b336c5e7e1732d4a1
